language: scala

jdk: oraclejdk8

script:
   - sbt clean coverage  test

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/a4b5f6fe6db37a780d74
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  slack: coaticservice:X4TsZaCjbh1uTE6rxgTsmez3