#!/usr/bin/env bash

. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/script-helper"

echo "+----------------------------+"
echo "| Executing tests using sbt  |"
echo "+----------------------------+"
cd ./src/main/g8
sbt ++$TRAVIS_SCALA_VERSION test